BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_press: input_name.text = ''
        on_press: output_label.text = 'Enter your name'
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)